package modelo;
// Generated 28/03/2019 11:09:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {


     private int idCalificacion;
     private Usuario usuario;
     private int puntaje;
     private Set comentarios = new HashSet(0);

    public Calificacion() {
    }

	
    public Calificacion(int idCalificacion, Usuario usuario, int puntaje) {
        this.idCalificacion = idCalificacion;
        this.usuario = usuario;
        this.puntaje = puntaje;
    }
    public Calificacion(int idCalificacion, Usuario usuario, int puntaje, Set comentarios) {
       this.idCalificacion = idCalificacion;
       this.usuario = usuario;
       this.puntaje = puntaje;
       this.comentarios = comentarios;
    }
   
    public int getIdCalificacion() {
        return this.idCalificacion;
    }
    
    public void setIdCalificacion(int idCalificacion) {
        this.idCalificacion = idCalificacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(int puntaje) {
        this.puntaje = puntaje;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


