package modelo;
// Generated 28/03/2019 11:09:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CatColor generated by hbm2java
 */
public class CatColor  implements java.io.Serializable {


     private int idColor;
     private String descripcion;
     private Set temas = new HashSet(0);

    public CatColor() {
    }

	
    public CatColor(int idColor, String descripcion) {
        this.idColor = idColor;
        this.descripcion = descripcion;
    }
    public CatColor(int idColor, String descripcion, Set temas) {
       this.idColor = idColor;
       this.descripcion = descripcion;
       this.temas = temas;
    }
   
    public int getIdColor() {
        return this.idColor;
    }
    
    public void setIdColor(int idColor) {
        this.idColor = idColor;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTemas() {
        return this.temas;
    }
    
    public void setTemas(Set temas) {
        this.temas = temas;
    }




}


