
package modelo;
// Generated 28/03/2019 11:09:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private int idMarcador;
     private Tema temaByIdColor;
     private Tema temaByIdTema;
     private double latitud;
     private double longitud;
     private String descripcion;
     private Set comentarios = new HashSet(0);

    public Marcador() {
    }

	
    public Marcador(int idMarcador, Tema temaByIdColor, Tema temaByIdTema, double latitud, double longitud) {
        this.idMarcador = idMarcador;
        this.temaByIdColor = temaByIdColor;
        this.temaByIdTema = temaByIdTema;
        this.latitud = latitud;
        this.longitud = longitud;
    }
    public Marcador(int idMarcador, Tema temaByIdColor, Tema temaByIdTema, double latitud, double longitud, String descripcion, Set comentarios) {
       this.idMarcador = idMarcador;
       this.temaByIdColor = temaByIdColor;
       this.temaByIdTema = temaByIdTema;
       this.latitud = latitud;
       this.longitud = longitud;
       this.descripcion = descripcion;
       this.comentarios = comentarios;
    }
   
    public int getIdMarcador() {
        return this.idMarcador;
    }
    
    public void setIdMarcador(int idMarcador) {
        this.idMarcador = idMarcador;
    }
    public Tema getTemaByIdColor() {
        return this.temaByIdColor;
    }
    
    public void setTemaByIdColor(Tema temaByIdColor) {
        this.temaByIdColor = temaByIdColor;
    }
    public Tema getTemaByIdTema() {
        return this.temaByIdTema;
    }
    
    public void setTemaByIdTema(Tema temaByIdTema) {
        this.temaByIdTema = temaByIdTema;
    }
    public double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }
    public double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }




}


