package modelo;
// Generated 28/03/2019 11:09:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private int idTema;
     private CatColor catColor;
     private Usuario usuario;
     private String nombreTema;
     private Set marcadorsForIdColor = new HashSet(0);
     private Set marcadorsForIdTema = new HashSet(0);

    public Tema() {
    }

	
    public Tema(int idTema, Usuario usuario) {
        this.idTema = idTema;
        this.usuario = usuario;
    }
    public Tema(int idTema, CatColor catColor, Usuario usuario, String nombreTema, Set marcadorsForIdColor, Set marcadorsForIdTema) {
       this.idTema = idTema;
       this.catColor = catColor;
       this.usuario = usuario;
       this.nombreTema = nombreTema;
       this.marcadorsForIdColor = marcadorsForIdColor;
       this.marcadorsForIdTema = marcadorsForIdTema;
    }
   
    public int getIdTema() {
        return this.idTema;
    }
    
    public void setIdTema(int idTema) {
        this.idTema = idTema;
    }
    public CatColor getCatColor() {
        return this.catColor;
    }
    
    public void setCatColor(CatColor catColor) {
        this.catColor = catColor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombreTema() {
        return this.nombreTema;
    }
    
    public void setNombreTema(String nombreTema) {
        this.nombreTema = nombreTema;
    }
    public Set getMarcadorsForIdColor() {
        return this.marcadorsForIdColor;
    }
    
    public void setMarcadorsForIdColor(Set marcadorsForIdColor) {
        this.marcadorsForIdColor = marcadorsForIdColor;
    }
    public Set getMarcadorsForIdTema() {
        return this.marcadorsForIdTema;
    }
    
    public void setMarcadorsForIdTema(Set marcadorsForIdTema) {
        this.marcadorsForIdTema = marcadorsForIdTema;
    }


    @Override
    public String toString(){
        return this.nombreTema;
    }


}


