package modelo;
// Generated 28/03/2019 11:09:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String correo;
     private String contrasenia;
     private String nombreUsuario;
     private String nombre;
     private String paterno;
     private Integer rol;
     private Set temas = new HashSet(0);
     private Set comentarios = new HashSet(0);
     private Set calificacions = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String correo, String contrasenia, String nombreUsuario) {
        this.correo = correo;
        this.contrasenia = contrasenia;
        this.nombreUsuario = nombreUsuario;
    }
    public Usuario(String correo, String contrasenia, String nombreUsuario, String nombre, String paterno, Integer rol, Set temas, Set comentarios, Set calificacions) {
       this.correo = correo;
       this.contrasenia = contrasenia;
       this.nombreUsuario = nombreUsuario;
       this.nombre = nombre;
       this.paterno = paterno;
       this.rol = rol;
       this.temas = temas;
       this.comentarios = comentarios;
       this.calificacions = calificacions;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }
    public Integer getRol() {
        return this.rol;
    }
    
    public void setRol(Integer rol) {
        this.rol = rol;
    }
    public Set getTemas() {
        return this.temas;
    }
    
    public void setTemas(Set temas) {
        this.temas = temas;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }




}